### Получить корзину
GET /api/basket/getone/116 HTTP/1.1
Host: localhost:7000
Cookie: basketId=25

### Добавить в корзину
PUT /api/basket/product/1/append/5/1000 HTTP/1.1
Host: localhost:7000
Cookie: basketId=25

### Удалить из корзины
PUT /api/basket/product/1/remove HTTP/1.1
Host: localhost:7000
Cookie: basketId=25

### Увеличить количество
PUT /api/basket/product/1/increment/4 HTTP/1.1
Host: localhost:7000
Cookie: basketId=25

### Уменьшить количество
PUT /api/basket/product/1/decrement/2 HTTP/1.1
Host: localhost:7000
Cookie: basketId=25

### Очистить корзину
PUT /api/basket/clear HTTP/1.1
Host: localhost:7000
Cookie: basketId=25
